os:
- linux

language: generic

services:
- docker
#env:
#- TEST_ENV=current
#- TEST_ENV=new-baseline

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull mdolab/public:current
- docker run -t -d 
        --name app
        --mount "type=volume,src=$TRAVIS_HOME,target=/travis"
        mdolab/public:current
        /bin/bash
- docker ps -a

install:
- docker exec -it app /bin/bash -c "ls; pwd; rm -r $HOME/repos/pygeo;"

script:
- docker exec -it app /bin/bash -c "ls; pwd; cd $HOME/travis/pygeo/reg_tests; python run_reg_tests.py -nodiff"

after_script:
- docker rm -f app
