os:
- linux

language: generic

services:
- docker
#env:
#- TEST_ENV=current
#- TEST_ENV=new-baseline

before_install:
# the chown makes the mount in Docker owned by the user.
# Note that the 1000/1000 is the uid/gid in Docker, already pre-set
- ls -ltr ../
- ls -ltr
- sudo chown -R 1000:1000 ../
- sudo chmod -R 755 ../
- ls -ltr ../
- ls -ltr
- pwd
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull mdolab/public:current
- docker run -t -d 
        --name app
        --mount "type=bind,src=$(pwd),target=/home/mdolabuser/travis"
        mdolab/public:current
        /bin/bash
- docker ps -a

install:
- docker exec -it app /bin/bash -c "id -u; id -g; rm -rf /home/mdolabuser/repos/pygeo;"

script:
- docker exec -it app /bin/bash -c "ls -ltr; pwd; cd travis/pygeo/reg_tests; python run_reg_tests.py -nodiff"

after_script:
- docker rm -f app
