language: python

services:
  - docker

before_script:
- docker pull benjaminbrelje/mdolabfull:latest

script:
- docker run --rm benjaminbrelje/mdolabfull:latest /bin/sh -c ". /root/.bashrc && cd /root/repos/pygeo/tests && python -m pytest reg_tests"